global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "node-mongo-vm"
    static_configs:
      - targets: ["localhost:9100"]
        labels:
          instance: "rag-mongo-vm"

  - job_name: "node-airflow-vm"
    static_configs:
      - targets: ["10.178.0.4:9100"]
        labels:
          instance: "rag-airflow-vm"

  - job_name: "mongodb"
    static_configs:
      - targets: ["localhost:9216"]
        labels:
          instance: "rag-mongo-vm"
